### PR TITLE
Externalise DNS resolution on the NonBlockingStatsDClient.

### PR DESCRIPTION
**Pull request by fakraemer**
Restores the old behaviour to resolve the address at construction time and cache it for the lifetime of the client.

### CODE REVIEW

**Comment by ovesh** [comment]
This is close to perfect. If you don't mind, I'm going to make some minor modifications and then merge it in. The biggest change will be to not call `volatileAddressResolution()` from `staticAddressResolution()`, to avoid the extra `InetAddress.getByName(hostname)` which wasn't there in the original implementation. Instead, I'll just `return new InetSocketAddress(hostname, port)`

Sounds ok?

**Comment by fakraemer** [comment]
@ovesh apologies for the late reply, I currently have no decent internet access from my home, thus had to check this from work. The reason why we did that change is that if you choose static resolution, you would want to know if resolution fails eagerly. That means escaping with `StatsDClientException` in the constructor, which is not great but the [current contract](https://github.com/indeedeng/java-dogstatsd-client/blob/master/src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java#L192):

    try {
        this.clientChannel = DatagramChannel.open();
        this.address = new InetSocketAddress(hostname, port);
    } catch (Exception e) {
        throw new StatsDClientException("Failed to start StatsD client", e);
    }

Given that the address was in the try-catch, I can only assume that the original author wanted to escape if name resolution fails. However, that's not how that `InetSocketAddress` constructor works:

    public InetSocketAddress(String hostname, int port) {
        checkHost(hostname);
        InetAddress addr = null;
        String host = null;
        try {
            addr = InetAddress.getByName(hostname);
        } catch(UnknownHostException e) {
            host = hostname;
        }
        holder = new InetSocketAddressHolder(host, addr, checkPort(port));
    }

That means `addr` will be null and `hostname` will be set on the `InetSocketAddressHolder` if name resolution fails. The only time that constructor escapes is if your chosen port number is out of range or you handed in null pointers.

The `InetSocketAddress` is [handed over to `j.n.c.DatagramChannel#send`](https://github.com/indeedeng/java-dogstatsd-client/blob/master/src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java#L581), the `s.n.c.DatagramChannelImpl` I have here will run it through `s.n.c.Net#checkAddress`:

    static InetSocketAddress checkAddress(SocketAddress var0) {
        if(var0 == null) {
            throw new IllegalArgumentException();
        } else if(!(var0 instanceof InetSocketAddress)) {
            throw new UnsupportedAddressTypeException();
        } else {
            InetSocketAddress var1 = (InetSocketAddress)var0;
            if(var1.isUnresolved()) {
                throw new UnresolvedAddressException();
            } else {
                InetAddress var2 = var1.getAddress();
                if(!(var2 instanceof Inet4Address) && !(var2 instanceof Inet6Address)) {
                    throw new IllegalArgumentException("Invalid address type");
                } else {
                    return var1;
                }
            }
        }
    }

where `j.n.InetSocketAddress#isUnresolved`:

    public final boolean isUnresolved() {
        return holder.isUnresolved();
    }

and `j.n.InetSocketAddress.InetSocketAddressHolder#isUnresolved`:

    private boolean isUnresolved() {
        return addr == null;
    }

That means the code will only escape on an attempt to send to the unresolved host. Note that this is  `j.n.c.UnresolvedAddressException` instead of `j.n.UnknownHostException`. What do you think is desired behaviour, the old code lazily escaping on send? In that case you can't recover within the client's lifetime, since resolution is never re-attempted. Or escape eagerly during construction, at least you know that the address was valid at that point in time? I'm happy to change it back to the old behaviour, just wanted to make you aware that this old behaviour is a bit odd. Not that attempting resolution in the constructor and escaping if it fails is much better.

**Comment by ovesh** [comment]
That is a fantastic explanation. I'll merge in as is, plus minor style modifications in a separate commit.

**Comment by fakraemer** [comment]
No worries. I tell Matt that he can merge this PR in, then you can either raise a PR against his repository or merge his PR into your repo and do the style modifications there. Thanks again for your help!

**Pull request merged**
